# Minimal system required
language: php

# Use containerized infrastructure
sudo: false

# Supported PHP-Versions
php:
  - 7.3

# Run Docker Service
services:
  - docker

# Build Docker Machine from Dockerfile and connect GitHub files / init composer
before_install:
  - docker build -t koseven/koseven .
  - docker run -dtP --name koseven -v $(pwd):/tmp/koseven/ koseven/koseven
  - docker ps -a
  - docker exec koseven /bin/sh -c "cd /tmp/koseven; composer install"

# Execute commands which should make the build pass or fail
script:
  - docker exec koseven /bin/sh -c "cd /tmp/koseven; php vendor/bin/phpunit"

# Execute commands which should run after successful build
# We need to symbolic link to /tmp/koseven - dirty hack
after_success:
  - ln -s $(pwd) /tmp/koseven
  - sudo chmod -R 755 build
  - sudo chmod -R 755 /tmp
  - travis_retry vendor/bin/php-coveralls -v

# Disable E-Mail notifications
notifications:
  email: false