# Project language is PHP7
language: php

# Test on Ubuntu Xenial (16.04)
dist: xenial

# Supported PHP-Versions
php:
  - 7.0
  - 7.1
  - 7.2

# Execute this commands before installing dependencies
before_install:
  - composer self-update
  - composer validate

# Install dependencies
install:
  - composer install
  - printf "\n" | pecl install -f redis
  - printf "\n" | pecl install -f imagick
  - printf "\n" | pecl install -f apcu
  - printf "\n" | pecl install -f apcu_bc

# Execute commands before executing script (e.g Add extensions to php.ini)
before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

# Execute commands which should make the build pass or fail
script:
  - vendor/bin/phpunit

# Execute commands which should run after successful build
after_success:
  - travis_retry vendor/bin/php-coveralls

# Disable E-Mail notifications
notifications:
  email: false
