# Project language is PHP7
language: php

# Test on multiple Operating systems
os:
  - linux
  - windows

# Linux OS should be trusty (14.04.5 LTS) @TODO Maybe update linux os?
matrix:
  include:
    - os: linux
      dist: trusty

# Supported PHP-Versions
php:
  - 7.0
  - 7.1
  - 7.2

# Execute this commands before installing dependencies
before_install:
  - composer self-update
  - composer validate

# Install dependencies
install:
  - composer install

# Execute commands which should make the build pass or fail
script:
  - vendor/bin/phpunit

# Execute commands which should run after successful build
after_success:
  - travis_retry vendor/bin/php-coveralls

# Disable E-Mail notifications
notifications:
  email: false
