# Project language is PHP
language: php

# Use containerized infrastructure
sudo: required

# Test on Ubuntu Xenial (16.04)
dist: xenial

# Supported PHP-Versions
php:
  - 7.3

# Cache Composer's cache
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/pecl_cache

# Services to start (with their default configuration)
services:
  - redis-server
  - memcached
  - mysql

# Execute this commands before installing dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgnutls28-dev libcurl4-openssl-dev
  - composer self-update
  - composer validate
  - mysql -e 'CREATE DATABASE IF NOT EXISTS unittest;'

# Install dependencies
install:
  - composer require phwoolcon/ci-pecl-cacher -n
  - pecl list-files redis | grep -v 'not installed' || echo "\n" | vendor/bin/ci-pecl-install redis
  - pecl list-files imagick | grep -v 'not installed' || echo "\n" | vendor/bin/ci-pecl-install imagick
  - pecl list-files apcu | grep -v 'not installed' || echo "\n" | vendor/bin/ci-pecl-install apcu
  - pecl list-files yaml | grep -v 'not installed' || echo "\n" | vendor/bin/ci-pecl-install yaml
  - pecl list-files raphf | grep -v 'not installed' || echo "\n" | vendor/bin/ci-pecl-install raphf
  - pecl list-files propro | grep -v 'not installed' || echo "\n" | vendor/bin/ci-pecl-install propro
  - echo "\n" | pecl install -f pecl_http

# Execute commands before executing script (e.g Add extensions to php.ini)
before_script:
  - echo "extension = pecl_http.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

# Execute commands which should make the build pass or fail
script:
  - vendor/bin/phpunit

# Execute commands which should run after successful build
after_success:
  - travis_retry vendor/bin/php-coveralls

# Disable E-Mail notifications
notifications:
  email: false
