# Project language is PHP
language: php

# Use containerized infrastructure
sudo: false

# Test on Ubuntu Xenial (16.04)
dist: xenial

# Supported PHP-Versions
php:
  - 7.2
  - 7.3

# Cache Composer's cache
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/pecl_cache

# Also Test on Trusty (14.04 LTS)
matrix:
  include:
    - dist: trusty
      php: 7.2
    - dist: trusty
      php: 7.3

# Services to start (with their default configuration)
services:
  - redis-server
  - memcached
  - mysql

# Execute this commands before installing dependencies
before_install:
  - composer self-update
  - composer validate
  - composer require phwoolcon/ci-pecl-cacher -n
  - vendor/bin/ci-pecl-install redis
  - vendor/bin/ci-pecl-install imagick
  - vendor/bin/ci-pecl-install apcu
  - vendor/bin/ci-pecl-install yaml
  - mysql -e 'CREATE DATABASE IF NOT EXISTS unittest;'

# Install dependencies
install:
  - composer install -n

# Execute commands before executing script (e.g Add extensions to php.ini)
before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

# Execute commands which should make the build pass or fail
script:
  - vendor/bin/phpunit

# Execute commands which should run after successful build
after_success:
  - travis_retry vendor/bin/php-coveralls

# Disable E-Mail notifications
notifications:
  email: false
